In [11]:
import numpy as np
class board:
    def __init__(self,m=18,n=9):
        self.m=m
        self.n=n
    def add_obsticle(self,obsticles):
        self.obsticles=obsticles
    def add_pacman(self,pacman):
        if (pacman.x,pacman.y) not in self.obsticles :
            self.pacman=pacman
            return True
        return False
    def disp(self):
        b=np.zeros([self.m,self.n],dtype=np.int8)
        print(b)
class Pacman:
    def __init__(self,x,y,enviroment=None):
        self.x=x
        self.y=y
        self.enviroment=enviroment

In [13]:
b=board()
p=Pacman(5,3)
b.add_obsticle([(1,2),(2,3)])
if b.add_pacman(p):
    p.enviroment=b

b.disp()

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
