In [266]:
import numpy as np
class board:
    def __init__(self,m=18,n=9):
        self.m=m
        self.n=n
    def add_obsticle(self,obsticles):
        self.obsticles=obsticles
    def add_pacman(self,pacman):
        if (pacman.x,pacman.y) not in self.obsticles :
            self.pacman=pacman
            return True
        return False
    def request_move(self,w):
        if w==1 and (self.pacman.x,self.pacman.y+1) not in self.obsticles and self.pacman.y<self.m-1:
            self.pacman.y=self.pacman.y+1
        elif w==2 and (self.pacman.x+1,self.pacman.y) not in self.obsticles and self.pacman.x<self.n-1:
            self.pacman.x=self.pacman.x+1
        elif w==3 and (self.pacman.x,self.pacman.y-1) not in self.obsticles and self.pacman.y>0:
            self.pacman.y=self.pacman.y-1
        elif w==4 and (self.pacman.x-1,self.pacman.y) not in self.obsticles and self.pacman.x>0 :
            self.pacman.x=self.pacman.x-1
        return False

    def disp(self):
        b=np.zeros([self.m,self.n],dtype=np.int8)
        b[self.pacman.x,self.pacman.y]=1
        print(b)
class Pacman:
    def __init__(self,x,y,enviroment=None):
        self.x=x
        self.y=y
        self.enviroment=enviroment
    def move(self,w):
        if w not in [1,2,3,4]:
            return False
        else:
            if self.enviroment.request_move(w):
                if w==1:
                    self.y=self.y+1
                elif w==2:
                    self.x=self.x+1
                elif w==3:
                    self.y=self.y-1
                elif w==4 :
                    self.x=self.x-1
        

In [299]:
b=board()
p=Pacman(4,2)
b.add_obsticle([(100,100)])
if b.add_pacman(p):
    p.enviroment=b

b.disp()

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [306]:
p.move(1)
b.disp()


IndexError: index 9 is out of bounds for axis 1 with size 9

In [312]:
b.n

9